name: Test
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}
          fetch-depth: 5

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
                
          
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
    
      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test 

      - name: Build
        run: pnpm build


